services:
  back:
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
    ports:
      - "80:80"
    environment:
      TZ: "Europe/Moscow"
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: /app/main test
      interval: 30s
      timeout: 3s
      retries: 3
    deploy:
      placement:
       constraints:
         - "node.labels.TAG==prod"
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
